#pragma once
#include <consoleapi2.h>

#define RED_COLOR			FOREGROUND_RED
#define GREEN_COLOR			FOREGROUND_GREEN
#define BLUE_COLOR			FOREGROUND_BLUE
#define WHITE_COLOR			FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE
#define YELLOW_COLOR		FOREGROUND_RED | FOREGROUND_GREEN
#define PURPLE_COLOR		FOREGROUND_RED | FOREGROUND_BLUE
#define LIGHT_BLUE_COLOR	FOREGROUND_GREEN | FOREGROUND_BLUE

#define BORDER_COLOR		FOREGROUND_BLUE